### ISSUE TITLE
Revise the short description

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#1]
At the moment it’s just a copy of the first line of the long description. We also tend to leave protagonist names out. Maybe something like:

> An undergraduate student’s experiences at Sanford College, a fictional, upscale, liberal arts school in Jazz Age New England.

**Comment by kingrpaul** [comment]
Rewritten on standard ebooks at https://github.com/standardebooks/percy-marks_the-plastic-age
