### ISSUE TITLE
Missing roman semantics for I

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#10]
We can’t automatically add roman semantics for `I`. Can you sweep for them? I found a couple (`Math I`) at https://github.com/kingrpaul/percy-marks_the-plastic-age/blob/15b462131c30fa3a0481b049e65607eb7fc38c04/src/epub/text/chapter-5.xhtml#L38

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/percy-marks_the-plastic-age/commit/cd161017833868f47d2177d70098f6de9d0daead
