### ISSUE TITLE
Typo with “marpessa”

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#11]
`marpessa` needs an initial capitalisation at https://github.com/kingrpaul/percy-marks_the-plastic-age/blob/15b462131c30fa3a0481b049e65607eb7fc38c04/src/epub/text/chapter-21.xhtml#L64

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/percy-marks_the-plastic-age/commit/4fcbe4ddb851f6b5e4d9b4c5c6410d353d15d153
