### ISSUE TITLE
Rubaiyat is a book so needs italics

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#12]
Rubaiyat is a book, so remove quotes and add italics with a book semantic: https://standardebooks.org/manual/1.4.0/single-page#8.2.11.2 . Can you sweep for other books too? Poems can stay as they are, unless they’re book-length.

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/percy-marks_the-plastic-age/commit/41153cb9536796e71f053477cd06bd5ff3b4fa6c
