### ISSUE TITLE
Revise the long description

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#2]
1. Replace `This novel` with `<i>The Plastic Age</i>`.
2. Can we expand the first paragraph with another sentence or two? A long description should be “as detailed as possible without giving away plot spoilers” https://standardebooks.org/manual/1.4.0/single-page#9.6.2.1

**Comment by kingrpaul** [comment]
Rewritten on standard ebooks at https://github.com/standardebooks/percy-marks_the-plastic-age
