### ISSUE TITLE
Wrong artist Wikipedia link in colophon

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#3]
https://github.com/kingrpaul/percy-marks_the-plastic-age/blob/15b462131c30fa3a0481b049e65607eb7fc38c04/src/epub/text/colophon.xhtml#L30

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/percy-marks_the-plastic-age/commit/18b9e964d1023dddc662b344e0f5dd1f890e0f6e
