### ISSUE TITLE
Some missing name abbreviations

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#4]
There are a few missing name abbreviations (e.g. `Henry W. Wordsworth` should be `Henry <abbr class="name">W.</abbr> Wordsworth`). A regex like `\b[A-Z]\.` will usually find them.

**Comment by kingrpaul** [comment]
appreciate the helpful regexes and links btw

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/percy-marks_the-plastic-age/commit/e84f2d09e448592dcbf9edc41b34af10dcec3832
