### ISSUE TITLE
Add continued class after in-dialog verse

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#6]
Where verse is quoted in a piece of dialog then you should use `class="continued"` on the following paragraph to remove the indent. Can you do a sweep for this? One place where this should be added is https://github.com/kingrpaul/percy-marks_the-plastic-age/blob/15b462131c30fa3a0481b049e65607eb7fc38c04/src/epub/text/chapter-11.xhtml#L54

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/percy-marks_the-plastic-age/commit/6fda5405fae58fcde0b42389ffe4f0d67b68268a
