### ISSUE TITLE
Use standard indentation classes and styles for verse

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/percy-marks_the-plastic-age#7]
We have our own standard for indentation (https://standardebooks.org/manual/1.4.0/single-page#7.5.4) which the poem in chapter 11 will need migrating to.

https://github.com/kingrpaul/percy-marks_the-plastic-age/blob/15b462131c30fa3a0481b049e65607eb7fc38c04/src/epub/text/chapter-11.xhtml#L69-L105

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/percy-marks_the-plastic-age/commit/42122a01b5f32199ad5f817d5d98b17898d5692c
Note that words no longer quite line up from line to line in agreement with the page scans.
